name: Atualizar GitHub Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Criar pasta assets
        run: mkdir -p assets

      - name: Baixar GitHub Stats
        run: |
          curl --fail --location --retry 3 --retry-delay 5 \
          -H "User-Agent: Mozilla/5.0" \
          "https://github-readme-stats.vercel.app/api?username=DannSouz&show_icons=true&hide_border=true&bg_color=fff0f6&title_color=ff69b4&text_color=8a4f6b&icon_color=ff8fab" \
          -o assets/github-stats.svg

      - name: Baixar linguagens
        run: |
          curl --fail --location --retry 3 --retry-delay 5 \
          -H "User-Agent: Mozilla/5.0" \
          "https://github-readme-stats.vercel.app/api/top-langs/?username=DannSouz&layout=compact&langs_count=6&hide_border=true&bg_color=fff0f6&title_color=ff69b4&text_color=8a4f6b" \
          -o assets/top-langs.svg

      - name: Validar arquivos
        run: |
          grep -q "<svg" assets/github-stats.svg
          grep -q "<svg" assets/top-langs.svg

      - name: Salvar cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/github-stats.svg assets/top-langs.svg
          git commit -m "Atualiza GitHub Stats" || exit 0
          git push
